mkdir fitmllmth
cd fitmllmth

combineCards.py hww_sr_2j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_2j/mllVSmth/datacard.txt hww_sr_mp_0j_pt2ge20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_mp_0j_pt2ge20/mllVSmth/datacard.txt hww_sr_mp_0j_pt2lt20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_mp_0j_pt2lt20/mllVSmth/datacard.txt hww_sr_mp_1j_pt2ge20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_mp_1j_pt2ge20/mllVSmth/datacard.txt hww_sr_mp_1j_pt2lt20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_mp_1j_pt2lt20/mllVSmth/datacard.txt hww_sr_pm_0j_pt2ge20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_pm_0j_pt2ge20/mllVSmth/datacard.txt hww_sr_pm_0j_pt2lt20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_pm_0j_pt2lt20/mllVSmth/datacard.txt hww_sr_pm_1j_pt2ge20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_pm_1j_pt2ge20/mllVSmth/datacard.txt hww_sr_pm_1j_pt2lt20=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/hww_sr_pm_1j_pt2lt20/mllVSmth/datacard.txt dyttcr_0j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/dyttcr_0j/events/datacard.txt dyttcr_1j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/dyttcr_1j/events/datacard.txt dyttcr_2j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/dyttcr_2j/events/datacard.txt topcr_0j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/topcr_0j/events/datacard.txt topcr_1j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/topcr_1j/events/datacard.txt topcr_2j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/topcr_2j/events/datacard.txt wwcr_0j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/wwcr_0j/events/datacard.txt wwcr_1j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/wwcr_1j/events/datacard.txt wwcr_2j=/afs/cern.ch/user/s/squinto/private/work/PlotsConfigurationsRun3/HWW/ggH_DF/2022/datacards/wwcr_2j/events/datacard.txt > fitmllmth.txt

text2workspace.py -P HiggsAnalysis.CombinedLimit.PhysicsModel:multiSignalModel  --PO verbose --PO 'map=.*/ggH:r[1,0,10]' --PO 'map=.*/qqH:r' fitmllmth.txt workspace.root

combine -M MultiDimFit --algo grid --points 50 --rMin 0.5 --rMax 1.5 -t -1 --setParameters r=1 --redefineSignalPOIs=r fitmllmth.root -m 125 -n expected.nominal --cminDefaultMinimizerStrategy 0

combine -M MultiDimFit --algo none --rMin 0.5 --rMax 1.5 -t -1 --setParameters r=1 --redefineSignalPOIs=r fitmllmth.root -m 125 -n expected.bestfit --cminDefaultMinimizerStrategy 0 --saveWorkspace

combine -M MultiDimFit --algo grid --points 50 --rMin 0.5 --rMax 1.5 -t -1 --setParameters r=1 --redefineSignalPOIs=r -m 125 -n expected.stat higgsCombineexpected.bestfit.MultiDimFit.mH125.root --snapshotName MultiDimFit --freezeParameters allConstrainedNuisances --cminDefaultMinimizerStrategy 0

plot1DScan.py higgsCombineexpected.nominal.MultiDimFit.mH125.root --main-label "stat. + syst." --POI r --others 'higgsCombineexpected.stat.MultiDimFit.mH125.root:stat.:2' --breakdown syst,stat

cd ..