cd ../scripts/

if [[ "$(uname -a)" == *portal* ]] || [[ "$(uname -a)" == *bms* ]]; then
    echo "We are at KIT!"
    input_dir=/ceph/${USER}
else
    echo "We are on lxplus!"
    input_dir=/eos/user/${USER:0:1}/${USER}
fi

# Muons
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet45.root --jet_pt 45 --flavor muon --variable conept2_eta2 --do_prompt_rate True --outputFileNamePR MuonPR.root

python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet10.root --jet_pt 10 --flavor muon --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet15.root --jet_pt 15 --flavor muon --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet20.root --jet_pt 20 --flavor muon --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet25.root --jet_pt 25 --flavor muon --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet30.root --jet_pt 30 --flavor muon --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet35.root --jet_pt 35 --flavor muon --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet40.root --jet_pt 40 --flavor muon --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cut_TightID_pfIsoTight_HWW_tthmva_67 --outputFileName MuonFR_jet45.root --jet_pt 45 --flavor muon --variable conept1_eta1

# Electrons
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet45.root --jet_pt 45 --flavor ele --variable conept2_eta2 --do_prompt_rate True --outputFileNamePR ElePR.root

python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet10.root --jet_pt 10 --flavor ele --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet15.root --jet_pt 15 --flavor ele --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet20.root --jet_pt 20 --flavor ele --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet25.root --jet_pt 25 --flavor ele --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet30.root --jet_pt 30 --flavor ele --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet35.root --jet_pt 35 --flavor ele --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet40.root --jet_pt 40 --flavor ele --variable conept1_eta1
python mkFakeRate.py --inputFile ${input_dir}/rootFiles/FakeRate/2022EEv12/rootFiles__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67/mkShapes__2022EEv12_cutBased_LooseID_tthMVA_Run3__mu_cut_TightID_pfIsoTight_HWW_tthmva_67.root --outputFolder /eos/user/s/squinto/FakeRate/2022EE_v12_conept/cutBased_LooseID_tthMVA_Run3 --outputFileName EleFR_jet45.root --jet_pt 45 --flavor ele --variable conept1_eta1

cd -
